apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: monitoring
spec:
  volumeName: pv-azuredisk-grafana
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 4Gi 